import { TriviQuestion } from './types';

/**
 * 60 general-knowledge trivia questions designed for calibration training.
 *
 * Design principles:
 * - Mix of easy (20), medium (20), hard (20) across 10 categories
 * - Some "trick" questions where the obvious answer is wrong (tests overconfidence)
 * - Some questions where most people know the answer but feel uncertain (tests underconfidence)
 * - Varied difficulty so users naturally give different confidence levels
 * - Categories: science, geography, history, math, nature, language, psychology,
 *   technology, music, literature
 */
export const QUESTION_BANK: TriviQuestion[] = [
  // ─── Easy (10) ────────────────────────────────────────────────────
  {
    id: 'e1',
    question: 'What is the chemical symbol for water?',
    options: ['H2O', 'CO2', 'NaCl', 'O2'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'easy',
  },
  {
    id: 'e2',
    question: 'Which continent is Brazil located on?',
    options: ['Africa', 'South America', 'Europe', 'Asia'],
    correctIndex: 1,
    category: 'geography',
    difficulty: 'easy',
  },
  {
    id: 'e3',
    question: 'How many days are in a leap year?',
    options: ['364', '365', '366', '367'],
    correctIndex: 2,
    category: 'math',
    difficulty: 'easy',
  },
  {
    id: 'e4',
    question: 'What gas do plants absorb from the atmosphere during photosynthesis?',
    options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    correctIndex: 2,
    category: 'science',
    difficulty: 'easy',
  },
  {
    id: 'e5',
    question: 'Which planet is closest to the Sun?',
    options: ['Venus', 'Earth', 'Mars', 'Mercury'],
    correctIndex: 3,
    category: 'science',
    difficulty: 'easy',
  },
  {
    id: 'e6',
    question: 'What is the largest ocean on Earth?',
    options: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean'],
    correctIndex: 3,
    category: 'geography',
    difficulty: 'easy',
  },
  {
    id: 'e7',
    question: 'In which year did World War II end?',
    options: ['1943', '1944', '1945', '1946'],
    correctIndex: 2,
    category: 'history',
    difficulty: 'easy',
  },
  {
    id: 'e8',
    question: 'What is the square root of 144?',
    options: ['10', '11', '12', '14'],
    correctIndex: 2,
    category: 'math',
    difficulty: 'easy',
  },
  {
    id: 'e9',
    question: 'Which animal is known as the "King of the Jungle"?',
    options: ['Tiger', 'Elephant', 'Lion', 'Gorilla'],
    correctIndex: 2,
    category: 'nature',
    difficulty: 'easy',
  },
  {
    id: 'e10',
    question: 'How many letters are in the English alphabet?',
    options: ['24', '25', '26', '27'],
    correctIndex: 2,
    category: 'language',
    difficulty: 'easy',
  },

  // ─── Medium (10) ──────────────────────────────────────────────────
  {
    id: 'm1',
    question: 'What is the capital of Australia?',
    options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
    correctIndex: 2,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'm2',
    question: 'Which element has the atomic number 79?',
    options: ['Silver', 'Platinum', 'Gold', 'Copper'],
    correctIndex: 2,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'm3',
    question: 'The Great Wall of China was primarily built to protect against invasions from which direction?',
    options: ['South', 'East', 'West', 'North'],
    correctIndex: 3,
    category: 'history',
    difficulty: 'medium',
  },
  {
    id: 'm4',
    question: 'What is the value of pi rounded to two decimal places?',
    options: ['3.12', '3.14', '3.16', '3.18'],
    correctIndex: 1,
    category: 'math',
    difficulty: 'medium',
  },
  {
    id: 'm5',
    question: 'Which language has the most native speakers worldwide?',
    options: ['English', 'Spanish', 'Mandarin Chinese', 'Hindi'],
    correctIndex: 2,
    category: 'language',
    difficulty: 'medium',
  },
  {
    id: 'm6',
    question: 'How many hearts does an octopus have?',
    options: ['1', '2', '3', '4'],
    correctIndex: 2,
    category: 'nature',
    difficulty: 'medium',
  },
  {
    id: 'm7',
    question: 'Which planet has the most moons in our solar system?',
    options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'],
    correctIndex: 1,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'm8',
    question: 'In what year was the United Nations founded?',
    options: ['1942', '1945', '1948', '1950'],
    correctIndex: 1,
    category: 'history',
    difficulty: 'medium',
  },
  {
    id: 'm9',
    question: 'What is the longest river in Africa?',
    options: ['Congo', 'Niger', 'Zambezi', 'Nile'],
    correctIndex: 3,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'm10',
    question: 'How many bones does an adult human body have?',
    options: ['186', '196', '206', '216'],
    correctIndex: 2,
    category: 'science',
    difficulty: 'medium',
  },

  // ─── Hard (10) — includes several "trick" questions ───────────────
  {
    id: 'h1',
    question: 'Which country has the longest coastline in the world?',
    options: ['Australia', 'Russia', 'Indonesia', 'Canada'],
    correctIndex: 3,
    category: 'geography',
    difficulty: 'hard',
  },
  {
    id: 'h2',
    question: 'What is the hardest natural substance on Earth?',
    options: ['Titanium', 'Diamond', 'Tungsten', 'Quartz'],
    correctIndex: 1,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'h3',
    question: 'The Hundred Years\' War lasted approximately how many years?',
    options: ['100', '106', '116', '126'],
    correctIndex: 2,
    category: 'history',
    difficulty: 'hard',
  },
  {
    id: 'h4',
    question: 'What percentage of the Earth\'s water is fresh water?',
    options: ['About 3%', 'About 10%', 'About 20%', 'About 30%'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'h5',
    question: 'Which of these animals sleeps the most hours per day?',
    options: ['Cat', 'Sloth', 'Koala', 'Python'],
    correctIndex: 2,
    category: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'h6',
    question: 'What is the smallest country in the world by area?',
    options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'],
    correctIndex: 1,
    category: 'geography',
    difficulty: 'hard',
  },
  {
    id: 'h7',
    question: 'In mathematics, what is the sum of all interior angles of a hexagon?',
    options: ['540 degrees', '600 degrees', '720 degrees', '900 degrees'],
    correctIndex: 2,
    category: 'math',
    difficulty: 'hard',
  },
  {
    id: 'h8',
    question: 'Which language is "Esperanto" most closely based on?',
    options: ['Latin and Romance languages', 'Germanic languages', 'Slavic languages', 'Greek'],
    correctIndex: 0,
    category: 'language',
    difficulty: 'hard',
  },
  {
    id: 'h9',
    question: 'What is the most abundant gas in Earth\'s atmosphere?',
    options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Argon'],
    correctIndex: 2,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'h10',
    question: 'The Panama Canal connects the Atlantic Ocean to which other ocean?',
    options: ['Indian Ocean', 'Pacific Ocean', 'Arctic Ocean', 'Southern Ocean'],
    correctIndex: 1,
    category: 'geography',
    difficulty: 'hard',
  },

  // ─── Easy — Wave 2 (10) ─────────────────────────────────────────
  {
    id: 'e11',
    question: 'Which weighs more: a ton of feathers or a ton of bricks?',
    options: ['Feathers', 'Bricks', 'They weigh the same', 'It depends on the type of feathers'],
    correctIndex: 2,
    category: 'science',
    difficulty: 'easy',
  },
  {
    id: 'e12',
    question: 'What instrument has 88 keys?',
    options: ['Guitar', 'Violin', 'Piano', 'Accordion'],
    correctIndex: 2,
    category: 'music',
    difficulty: 'easy',
  },
  {
    id: 'e13',
    question: 'What is the term for a fear of spiders?',
    options: ['Claustrophobia', 'Arachnophobia', 'Acrophobia', 'Hydrophobia'],
    correctIndex: 1,
    category: 'psychology',
    difficulty: 'easy',
  },
  {
    id: 'e14',
    question: 'What does "www" stand for in a website address?',
    options: ['World Wide Web', 'Western Web Works', 'Wide World Website', 'Web World Wide'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'easy',
  },
  {
    id: 'e15',
    question: 'Who wrote "Romeo and Juliet"?',
    options: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain'],
    correctIndex: 1,
    category: 'literature',
    difficulty: 'easy',
  },
  {
    id: 'e16',
    question: 'What is the boiling point of water at sea level in Celsius?',
    options: ['90°C', '100°C', '110°C', '120°C'],
    correctIndex: 1,
    category: 'science',
    difficulty: 'easy',
  },
  {
    id: 'e17',
    question: 'How many strings does a standard guitar have?',
    options: ['4', '5', '6', '8'],
    correctIndex: 2,
    category: 'music',
    difficulty: 'easy',
  },
  {
    id: 'e18',
    question: 'What is the binary number system based on?',
    options: ['0 and 1', '1 and 2', '0 and 9', '1 and 10'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'easy',
  },
  {
    id: 'e19',
    question: 'In which direction does the sun rise?',
    options: ['West', 'North', 'South', 'East'],
    correctIndex: 3,
    category: 'geography',
    difficulty: 'easy',
  },
  {
    id: 'e20',
    question: 'What colour do you get when you mix red and white?',
    options: ['Orange', 'Purple', 'Pink', 'Peach'],
    correctIndex: 2,
    category: 'science',
    difficulty: 'easy',
  },

  // ─── Medium — Wave 2 (10) ───────────────────────────────────────
  {
    id: 'm11',
    question: 'How many time zones does China officially use?',
    options: ['3', '4', '5', '1'],
    correctIndex: 3,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'm12',
    question: 'What is the name of the psychological phenomenon where people in a group are less likely to help someone in need?',
    options: ['Halo effect', 'Bystander effect', 'Placebo effect', 'Dunning-Kruger effect'],
    correctIndex: 1,
    category: 'psychology',
    difficulty: 'medium',
  },
  {
    id: 'm13',
    question: 'What programming language was created by Guido van Rossum in 1991?',
    options: ['Java', 'C++', 'Python', 'Ruby'],
    correctIndex: 2,
    category: 'technology',
    difficulty: 'medium',
  },
  {
    id: 'm14',
    question: 'Which novel begins with the line "Call me Ishmael"?',
    options: ['The Great Gatsby', 'Moby-Dick', '1984', 'Don Quixote'],
    correctIndex: 1,
    category: 'literature',
    difficulty: 'medium',
  },
  {
    id: 'm15',
    question: 'In music, how many notes are in a chromatic scale?',
    options: ['7', '8', '10', '12'],
    correctIndex: 3,
    category: 'music',
    difficulty: 'medium',
  },
  {
    id: 'm16',
    question: 'What percentage of the ocean floor has been mapped in high resolution?',
    options: ['About 5%', 'About 25%', 'About 50%', 'About 75%'],
    correctIndex: 1,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'm17',
    question: 'What does the psychological term "cognitive dissonance" describe?',
    options: ['Memory loss under stress', 'Discomfort from holding contradictory beliefs', 'Inability to make decisions', 'Fear of new experiences'],
    correctIndex: 1,
    category: 'psychology',
    difficulty: 'medium',
  },
  {
    id: 'm18',
    question: 'Which scientist is credited with developing the World Wide Web?',
    options: ['Vint Cerf', 'Tim Berners-Lee', 'Alan Turing', 'Steve Wozniak'],
    correctIndex: 1,
    category: 'technology',
    difficulty: 'medium',
  },
  {
    id: 'm19',
    question: 'Who wrote "One Hundred Years of Solitude"?',
    options: ['Pablo Neruda', 'Jorge Luis Borges', 'Gabriel García Márquez', 'Isabel Allende'],
    correctIndex: 2,
    category: 'literature',
    difficulty: 'medium',
  },
  {
    id: 'm20',
    question: 'What is the speed of light in a vacuum, approximately?',
    options: ['300,000 km/s', '150,000 km/s', '500,000 km/s', '1,000,000 km/s'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'medium',
  },

  // ─── Hard — Wave 2 (10) — includes calibration-testing questions ─
  {
    id: 'h11',
    question: 'Which planet in our solar system rotates on its side with an axial tilt of about 98 degrees?',
    options: ['Neptune', 'Saturn', 'Uranus', 'Pluto'],
    correctIndex: 2,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'h12',
    question: 'The Dunning-Kruger effect describes a bias where people with low ability tend to:',
    options: ['Underestimate their competence', 'Overestimate their competence', 'Accurately assess their competence', 'Refuse to assess their competence'],
    correctIndex: 1,
    category: 'psychology',
    difficulty: 'hard',
  },
  {
    id: 'h13',
    question: 'What was the first programmable general-purpose electronic computer?',
    options: ['UNIVAC', 'ENIAC', 'Colossus', 'Z3'],
    correctIndex: 1,
    category: 'technology',
    difficulty: 'hard',
  },
  {
    id: 'h14',
    question: 'Who wrote "Things Fall Apart"?',
    options: ['Wole Soyinka', 'Chinua Achebe', 'Ngũgĩ wa Thiong\'o', 'Chimamanda Ngozi Adichie'],
    correctIndex: 1,
    category: 'literature',
    difficulty: 'hard',
  },
  {
    id: 'h15',
    question: 'In Western music theory, what interval is known as the "devil\'s interval"?',
    options: ['Minor second', 'Tritone', 'Major seventh', 'Diminished fifth'],
    correctIndex: 1,
    category: 'music',
    difficulty: 'hard',
  },
  {
    id: 'h16',
    question: 'Approximately how many neurons are in the adult human brain?',
    options: ['86 million', '860 million', '8.6 billion', '86 billion'],
    correctIndex: 3,
    category: 'psychology',
    difficulty: 'hard',
  },
  {
    id: 'h17',
    question: 'What is the most widely used database query language?',
    options: ['NoSQL', 'GraphQL', 'SQL', 'MongoDB'],
    correctIndex: 2,
    category: 'technology',
    difficulty: 'hard',
  },
  {
    id: 'h18',
    question: 'In which century was "The Tale of Genji", often considered the world\'s first novel, written?',
    options: ['8th century', '11th century', '14th century', '6th century'],
    correctIndex: 1,
    category: 'literature',
    difficulty: 'hard',
  },
  {
    id: 'h19',
    question: 'A standard piano keyboard spans how many octaves?',
    options: ['5', '6', 'Just over 7', '8'],
    correctIndex: 2,
    category: 'music',
    difficulty: 'hard',
  },
  {
    id: 'h20',
    question: 'Mount Chimborazo in Ecuador is farther from Earth\'s center than Mount Everest. Why?',
    options: ['It is taller', 'Earth bulges at the equator', 'Ecuador has lower sea level', 'Measurement error in Everest\'s height'],
    correctIndex: 1,
    category: 'geography',
    difficulty: 'hard',
  },
];

/**
 * Randomly select `count` questions from the question bank,
 * using a Fisher-Yates shuffle for uniform randomness.
 */
export function pickRandomQuestions(count: number = 10): TriviQuestion[] {
  const pool = [...QUESTION_BANK];
  // Fisher-Yates shuffle
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, Math.min(count, pool.length));
}
